language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
  - lts/*
env:
  matrix:
  - TEST_BROWSER_NAME=chrome TEST_BROWSER_OS='Windows 10'
  - TEST_BROWSER_NAME=firefox TEST_BROWSER_OS='Windows 10'
before_script: npm install -g karma-cli
addons:
  sauce_connect:
    username: "CendioOssman"
  jwt:
    secure: "gdZp442zV7p09XJCTj2kaakXWC7DR4w99ln0DC2Y6YkE85XbBrI1Lm/22O9uMm5i117QIZ6wTs5T+t4zT4C4MRDDlSOgwQj/PitiXQJWkq4mt/LzeWbHP9ArckXLhSiweCp1/uriqsHtdslDhW5QlUGvjGPlGOj9LS8Fd1yJBEs="
